### ISSUE TITLE
Support multiple schema

### ISSUE THREAD

**Issue by petrus-v** [tartiflette/tartiflette-asgi#107]
As far I understand the code [multiple schema](https://tartiflette.io/docs/api/schema-registry) is not yet possible using v0.7.1.

I'm not sure if I needs it yet, so I won't start working on it right now.

**Comment by florimondmanca** [comment]
Hmm.

What would “multiple schema” support involve on our side?

I _believe_ (?) currently there’s a schema parameter on TartifletteApp - maybe it’s not documented. Is that enough?

**Comment by petrus-v** [comment]
I guessed from the linked example, if someone wants to manage multiple schema from one route that he have to provide one engine per schema.

I'm not sure if it's a good practice, I don't really needs it at the moment so I'll close this the moment and clarify my ideas !

thanks
