### ISSUE TITLE
Update banner

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-asgi#83]
With this project now named `tartiflette-asgi`, the current banner is outdated because it mentions "Tartiflette + Starlette".

We should update the logo to read "Tartiflette + ASGI" — probably with "ASGI" written in plain text (as ASGI doesn't currenly have a logo AFAIK).

@tsunammis Do you still have the editable logo file?

**Comment by tsunammis** [comment]
is it ok for you?

**Comment by florimondmanca** [comment]
The new banner looks great, thanks!
