### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by florimondmanca** [tartiflette/tartiflette-asgi#86]
All documentation for this package currently lives in the README of this repo. I think it's *okay*, but READMEs tend to be hard to read and navigate as soon as you have more than an installation/quickstart/learn more structure.

I'm considering building a simple docs site with [MkDocs](https://github.com/encode/mkdocs). It recently acquired [autodoc](https://github.com/tomchristie/mkautodoc) features, which I think is an extra nice thing to have/try out.

We can setup MkDocs independently, and then see if we add the current docs or review them first before deploying the new docs site.

The only unknown here is hosting. GitHub Pages seems like a sensible solution (in particular because MkDocs has built-in support for deploying to GitHub Pages).

@tsunammis / @abusi Are we OK with hosting the docs site at https://tartiflette.github.io/tartiflette-asgi? I don't think there's any setup or steps required on your side, just making sure the Tartiflette org doesn't already have a docs hosting solution in place.

**Comment by abusi** [comment]
I think we should work on integrating this future doc into the tartiflette.io one. (Which is a ghpage). @tsunammis what do you think ?

**Comment by florimondmanca** [comment]
I'd be fine with that, though I think it'd be nice for `tartiflette-asgi` to have its own space there somehow, i.e. not be interlinked too much with the body of the Tartiflette-specific documentation. I'm thinking of e.g. adding a "Transports" tab in the navbar, with a dropdown showing `tartiflette-asgi` (and perhaps soon `tartiflette-aiohttp`?), and each link shows up a page (and sidebar) that's only dedicated to the specific transport library.

**Comment by abusi** [comment]
That's a good idea, the 'transport' navbar. Me likin' it.

**Comment by tsunammis** [comment]
This is ok for me to create a specific website for `tartiflette-asgi`.

We already have tartiflette.io (https://github.com/tartiflette/tartiflette.io/) which uses a custom domain. 

Just try to enable the static website. We will see how doesn't it work.

Regarding a "Transport" tab, We will talk about it internally with @abusi and @Maximilien-R to make sure that we are going on the right way for the tartiflette's HTTP wrappers.

**Comment by florimondmanca** [comment]
@tsunammis I opened #94 with the full docs site, but I wanted to try out deploying beforehand. I tried to push the `mkdocs` starter site from the first commit in #94:

```bash
git checkout 46945da
mkdocs gh-deploy
```

The GitHub Pages section of the settings page here looks good:

![Screenshot 2019-10-31 at 12 47 11](https://user-images.githubusercontent.com/15911462/67944384-a7e9b900-fbdc-11e9-82bf-e550f247a1d5.png)


But there isn't anything at https://tartiflette.github.io/tartiflette-asgi yet unfortunately:

Expected:

![Screenshot 2019-10-31 at 12 46 35](https://user-images.githubusercontent.com/15911462/67944331-825caf80-fbdc-11e9-90ef-2ddb4515993f.png)

Actual:

![Screenshot 2019-10-31 at 12 46 24](https://user-images.githubusercontent.com/15911462/67944340-8688cd00-fbdc-11e9-9023-f835bff38481.png)

Should I specify `tartiflette.io` as the custom domain, maybe?

**Comment by florimondmanca** [comment]
Oh, right, the site is actually accessible at https://tartiflette.github.io/tartiflette-asgi/index.html (note the `/index.html` suffix).

Need to figure out how to enable root serving on MkDocs.

**Comment by florimondmanca** [comment]
OK weird, I deployed again and the site is now up: https://tartiflette.github.io/tartiflette-asgi/

Looks like the infrastructure is all set! :+1:
